### PR TITLE
Add version support

### PR DESCRIPTION
**Pull request by radhe-zeeve**
## Resolves
- https://github.com/paritytech/ink-playground/issues/427
- https://github.com/paritytech/ink-playground/issues/460
- https://github.com/paritytech/ink-playground/issues/428

## Reference:
- https://github.com/w3f/Grants-Program/pull/1731

### CODE REVIEW

**Comment by cmichi** [comment]
@radhe-zeeve Is the PR intentionally in Draft? It seems ready to be merged to me?

**Comment by cmichi** [comment]
@radhe-zeeve CI is failing, but you should be able to see the log and fix it.

**Comment by radhe-zeeve** [comment]
@cmichi PR is ready for review. 

Couple of Github actions were modified to make the process faster and to mitigate the out of space issue. Following are the actions which were modified:
- `.github/workflows/docker.yml`: Multiple images of ink were downloaded in ink playground container and this caused the storage to be full, so after the successful image build, during container execution versions list was mounted with single version which was used in one of test case.
- `.github/workflows/compiler_docker.yml`: Only latest version image of ink compiler is been built, tagged and pushed to registry.

I have used my docker registry ID (`radhezeeve`) to push the images. and all the images part of this repository are public. The same registry ID is used in code base, which can be updated to older ID (`achimcc`) as soon as all the ink compiler images are updated on the older registry ID.

**Review by cmichi — APPROVED** [review]

**Comment by cmichi** [comment]
Thank you for working on this, @radhe-zeeve!

Unfortunately we have decided to archive this project, as we don't have the resources to operate it anymore. If you would be interested in doing so, please to the W3F. I know they also have maintenance grants, maybe that would be an option.

**Pull request merged**
